name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew app:test
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew app:detekt


